INSERT INTO site_content (cle, valeur, section, libelle, type, ordre) VALUES
('nav.menu', 'Menu', 'navigation', 'Libellé menu mobile', 'text', 1),
('nav.link.home', 'Accueil', 'navigation', 'Lien accueil', 'text', 2),
('nav.link.profile', 'Profil', 'navigation', 'Lien profil', 'text', 3),
('nav.link.services', 'Services', 'navigation', 'Lien services', 'text', 4),
('nav.link.calculator', 'Calculateur', 'navigation', 'Lien calculateur', 'text', 5),
('nav.link.faq', 'FAQ', 'navigation', 'Lien FAQ', 'text', 6),
('nav.link.application', 'Demande en ligne', 'navigation', 'Lien demande', 'text', 7),
('nav.link.contact', 'Nous joindre', 'navigation', 'Lien contact', 'text', 8),
('nav.service.particuliers', 'Services pour particuliers', 'navigation', 'Service particuliers', 'text', 9),
('nav.service.temporaire', 'Financement temporaire', 'navigation', 'Service financement temporaire', 'text', 10),
('nav.service.consolidation', 'Consolidation de dettes', 'navigation', 'Service consolidation', 'text', 11),
('nav.service.credit', '2e chance au crédit', 'navigation', 'Service 2e chance', 'text', 12),
('nav.service.entreprises', 'Services pour entreprises', 'navigation', 'Service entreprises', 'text', 13),
('nav.service.faillite', 'Éviter la faillite', 'navigation', 'Service faillite', 'text', 14),
('nav.cta', 'Faire une demande', 'navigation', 'Bouton CTA navigation', 'text', 15),

('faq.home.badge', 'Foire aux questions', 'faq', 'Badge FAQ accueil', 'text', 60),
('faq.home.titre', 'Questions fréquentes', 'faq', 'Titre FAQ accueil', 'text', 61),
('faq.home.soustitre', 'Tout ce que vous devez savoir sur nos services de financement', 'faq', 'Sous-titre FAQ accueil', 'text', 62),
('faq.home.empty', 'Aucune question n''est disponible pour le moment.', 'faq', 'État vide FAQ accueil', 'text', 63),
('faq.cta.bouton', 'Nous joindre', 'faq', 'Bouton CTA FAQ', 'text', 64),

('forms.submit.server_error', 'Le serveur a rencontré une erreur. Veuillez réessayer plus tard ou nous appeler au {phone}.', 'demande', 'Erreur serveur formulaires', 'text', 110),

('confirmation.title.default', 'Demande reçue !', 'confirmation', 'Titre par défaut', 'text', 1),
('confirmation.title.with_name', 'Merci {prenom} !', 'confirmation', 'Titre avec prénom', 'text', 2),
('confirmation.subtitle', 'Votre demande de financement a bien été soumise. Un spécialiste vous contactera dans les {delay}.', 'confirmation', 'Sous-titre confirmation', 'textarea', 3),
('confirmation.delay', '48 heures ouvrables', 'confirmation', 'Délai affiché', 'text', 4),
('confirmation.urgent.title', 'Besoin d''une réponse urgente ?', 'confirmation', 'Titre urgence', 'text', 5),
('confirmation.urgent.hours', 'Lun – Ven · 8h30 – 17h30', 'confirmation', 'Heures urgence', 'text', 6),
('confirmation.next.title', 'Ce qui arrive ensuite', 'confirmation', 'Titre étapes', 'text', 7),
('confirmation.step.1.title', 'Appel de qualification', 'confirmation', 'Étape 1 titre', 'text', 8),
('confirmation.step.1.desc', 'Un spécialiste vous contactera dans les 48 heures ouvrables.', 'confirmation', 'Étape 1 description', 'textarea', 9),
('confirmation.step.2.title', 'Préparation du dossier', 'confirmation', 'Étape 2 titre', 'text', 10),
('confirmation.step.2.desc', 'Rassemblez vos documents (liste ci-dessous) pour accélérer le traitement.', 'confirmation', 'Étape 2 description', 'textarea', 11),
('confirmation.step.3.title', 'Approbation & financement', 'confirmation', 'Étape 3 titre', 'text', 12),
('confirmation.step.3.desc', 'Une fois le dossier complet, nous travaillons à vous obtenir les meilleurs termes.', 'confirmation', 'Étape 3 description', 'textarea', 13),
('confirmation.documents.title', 'Documents à préparer pour votre dossier', 'confirmation', 'Titre documents', 'text', 14),
('confirmation.documents.items', 'Pièce d''identité avec photo (permis de conduire ou passeport)
Évaluation municipale de la propriété
Relevé hypothécaire récent (si applicable)
Preuve de propriété (acte de vente)
Preuve de revenus (derniers relevés de paie ou avis de cotisation)', 'confirmation', 'Liste documents', 'textarea', 15),
('confirmation.actions.home', 'Retour à l''accueil', 'confirmation', 'Bouton retour accueil', 'text', 16),
('confirmation.actions.retry', 'Soumettre une autre demande', 'confirmation', 'Bouton nouvelle demande', 'text', 17),
('confirmation.actions.empty', 'Vous n''avez pas encore rempli de demande ?', 'confirmation', 'Texte accès direct', 'text', 18),
('confirmation.actions.empty_link', 'Commencer maintenant', 'confirmation', 'Lien accès direct', 'text', 19),

('legal.hero.titre', 'Mentions légales', 'legal', 'Titre hero', 'text', 1),
('legal.hero.soustitre', 'Informations juridiques et réglementaires', 'legal', 'Sous-titre hero', 'text', 2),
('legal.editor.title', 'Éditeur du site', 'legal', 'Titre éditeur', 'text', 3),
('legal.editor.company_label', 'Raison sociale', 'legal', 'Label raison sociale', 'text', 4),
('legal.editor.company_value', 'Solutions Financement Fortier Inc.', 'legal', 'Valeur raison sociale', 'text', 5),
('legal.editor.legal_form_label', 'Forme juridique', 'legal', 'Label forme juridique', 'text', 6),
('legal.editor.legal_form_value', 'Société par actions (Québec)', 'legal', 'Valeur forme juridique', 'text', 7),
('legal.editor.publisher_label', 'Directeur et responsable de la publication', 'legal', 'Label publication', 'text', 8),
('legal.editor.publisher_value', 'Honoré Fortier', 'legal', 'Valeur publication', 'text', 9),
('legal.editor.address_label', 'Adresse', 'legal', 'Label adresse', 'text', 10),
('legal.editor.address_value', 'Province de Québec, Canada', 'legal', 'Valeur adresse', 'text', 11),
('legal.editor.phone_label', 'Téléphone', 'legal', 'Label téléphone', 'text', 12),
('legal.editor.email_label', 'Courriel', 'legal', 'Label courriel', 'text', 13),
('legal.editor.website_label', 'Site Web', 'legal', 'Label site web', 'text', 14),
('legal.editor.website_value', 'www.solutionsfortier.com', 'legal', 'Valeur site web', 'text', 15),
('legal.hosting.title', 'Hébergement', 'legal', 'Titre hébergement', 'text', 16),
('legal.hosting.provider_label', 'Hébergeur', 'legal', 'Label hébergeur', 'text', 17),
('legal.hosting.provider_value', 'Vercel Inc.', 'legal', 'Valeur hébergeur', 'text', 18),
('legal.hosting.address_label', 'Adresse', 'legal', 'Label adresse hébergeur', 'text', 19),
('legal.hosting.address_value', '340 S Lemon Ave #4133, Walnut, CA 91789, États-Unis', 'legal', 'Valeur adresse hébergeur', 'textarea', 20),
('legal.hosting.website_label', 'Site Web', 'legal', 'Label site hébergeur', 'text', 21),
('legal.hosting.website_value', 'vercel.com', 'legal', 'Valeur site hébergeur', 'text', 22),
('legal.ip.title', 'Propriété intellectuelle', 'legal', 'Titre propriété intellectuelle', 'text', 23),
('legal.ip.body', 'L''ensemble du contenu de ce site (textes, images, graphiques, logos, icônes, structure) est la propriété exclusive de Solutions Financement Fortier Inc. ou de ses partenaires. Toute reproduction, distribution, modification, adaptation, retransmission ou publication de ces éléments est strictement interdite sans l''accord écrit préalable de Solutions Financement Fortier Inc.', 'legal', 'Texte propriété intellectuelle', 'textarea', 24),
('legal.liability.title', 'Limitation de responsabilité', 'legal', 'Titre responsabilité', 'text', 25),
('legal.liability.body', 'Les informations présentées sur ce site le sont à titre indicatif et ne constituent pas un avis juridique, financier ou professionnel. Solutions Financement Fortier Inc. s''efforce de fournir des informations exactes et à jour, mais ne garantit pas l''exhaustivité ni l''exactitude de celles-ci. L''utilisation des informations se fait sous l''entière responsabilité du visiteur.', 'legal', 'Texte responsabilité', 'textarea', 26),
('legal.privacy.title', 'Données personnelles', 'legal', 'Titre données personnelles', 'text', 27),
('legal.privacy.prefix', 'Pour connaître la façon dont nous collectons, utilisons et protégeons vos données personnelles, veuillez consulter notre', 'legal', 'Préfixe données personnelles', 'textarea', 28),
('legal.privacy.link', 'Politique de confidentialité', 'legal', 'Libellé lien confidentialité', 'text', 29),
('legal.law.title', 'Loi applicable', 'legal', 'Titre loi applicable', 'text', 30),
('legal.law.body', 'Le présent site et ses mentions légales sont régis par les lois de la province de Québec et les lois fédérales canadiennes applicables. Tout litige sera soumis à la compétence exclusive des tribunaux du district judiciaire de Québec.', 'legal', 'Texte loi applicable', 'textarea', 31),
('legal.regulation.title', 'Réglementation applicable', 'legal', 'Titre réglementation', 'text', 32),
('legal.regulation.body', 'Solutions Financement Fortier Inc. exerce ses activités conformément à la législation québécoise en matière de prêt hypothécaire privé. Le prêt privé au Québec est encadré notamment par le Code civil du Québec, la Loi sur la protection du consommateur et la Loi sur les activités de courtage en prêt hypothécaire résidentiel.', 'legal', 'Texte réglementation', 'textarea', 33),

('notfound.meta.title', 'Page introuvable — Solutions Financement Fortier', 'notfound', 'Titre meta', 'text', 1),
('notfound.title', 'Page introuvable', 'notfound', 'Titre page', 'text', 2),
('notfound.description', 'Désolé, la page que vous recherchez n''existe pas ou a été déplacée.', 'notfound', 'Description', 'textarea', 3),
('notfound.home', 'Retour à l''accueil', 'notfound', 'Bouton accueil', 'text', 4),
('notfound.back', 'Page précédente', 'notfound', 'Bouton retour', 'text', 5),

('regions.hero.titre', 'Prêteur Alternatif au Québec — Toutes les Régions', 'regions', 'Titre hero régions', 'text', 1),
('regions.hero.soustitre', 'Solutions Financement Fortier dessert toute la province. Trouvez le financement alternatif dont vous avez besoin, peu importe votre ville.', 'regions', 'Sous-titre hero régions', 'textarea', 2),
('regions.intro', 'Depuis 1998, Solutions Financement Fortier offre des prêts avec garantie immobilière partout au Québec. Que vous soyez à Montréal, Québec, Gatineau ou dans une plus petite municipalité, nous pouvons vous aider avec un financement rapide, approuvé en 48 heures.', 'regions', 'Texte intro régions', 'textarea', 3),
('regions.cta.titre', 'Prêt à obtenir votre financement ?', 'regions', 'Titre CTA régions', 'text', 4),
('regions.cta.soustitre', 'Peu importe votre ville au Québec, nous pouvons vous aider. Réponse en 48 heures.', 'regions', 'Sous-titre CTA régions', 'textarea', 5),

('city.notfound.title', 'Ville introuvable', 'city', 'Titre ville introuvable', 'text', 1),
('city.notfound.description', 'Cette page de ville n''existe pas.', 'city', 'Description ville introuvable', 'text', 2),
('city.notfound.home', 'Retour à l''accueil', 'city', 'Bouton ville introuvable', 'text', 3),
('city.hero.titre_template', 'Prêteur Alternatif à {city}', 'city', 'Template hero titre', 'text', 4),
('city.hero.soustitre_template', 'Financement rapide avec garantie immobilière dans la région de {city}. Approbation en 48h, même avec un dossier de crédit difficile.', 'city', 'Template hero sous-titre', 'textarea', 5),
('city.intro.titre_template', 'Financement alternatif à {city}, {region}', 'city', 'Template intro titre', 'text', 6),
('city.intro.body1_template', 'Vous cherchez un prêteur alternatif à {city} ? Solutions Financement Fortier dessert la région de {city} et ses environs depuis 1998. Que vous soyez à {nearby} ou ailleurs dans {region}, nous offrons des solutions de financement adaptées à votre situation.', 'city', 'Template intro texte 1', 'textarea', 7),
('city.intro.body2_template', 'Notre bureau est situé à Fossambault-sur-le-Lac, à environ {distance} km de {city}. Nous servons toute la province du Québec avec des prêts garantis par des actifs immobiliers. Nos dossiers sont traités rapidement, avec une approbation possible en 48 heures.', 'city', 'Template intro texte 2', 'textarea', 8),
('city.trust.1', 'Approbation en 48h', 'city', 'Badge confiance 1', 'text', 9),
('city.trust.2', 'Confidentialité totale', 'city', 'Badge confiance 2', 'text', 10),
('city.trust.3', 'Depuis 1998', 'city', 'Badge confiance 3', 'text', 11),
('city.trust.4_template', '{phone}', 'city', 'Badge confiance 4', 'text', 12),
('city.services.titre_template', 'Nos services de financement à {city}', 'city', 'Template services titre', 'text', 13),
('city.services.card_desc_template', 'Disponible pour les résidents de {city} et de la région {region}.', 'city', 'Template services description', 'textarea', 14),
('city.services.particuliers', 'Financement pour particuliers', 'city', 'Service ville particuliers', 'text', 15),
('city.services.entreprises', 'Financement pour entreprises', 'city', 'Service ville entreprises', 'text', 16),
('city.services.financement-temporaire', 'Financement temporaire & prêt relais', 'city', 'Service ville financement temporaire', 'text', 17),
('city.services.consolidation-dettes', 'Consolidation de dettes', 'city', 'Service ville consolidation', 'text', 18),
('city.services.deuxieme-chance-credit', '2e chance au crédit', 'city', 'Service ville 2e chance', 'text', 19),
('city.services.eviter-faillite', 'Éviter la faillite', 'city', 'Service ville faillite', 'text', 20),
('city.services.more', 'En savoir plus', 'city', 'Libellé en savoir plus', 'text', 21),
('city.why.titre_template', 'Pourquoi choisir un prêteur alternatif à {city} ?', 'city', 'Template pourquoi titre', 'text', 22),
('city.why.1.titre', 'Refusé par les banques ?', 'city', 'Pourquoi 1 titre', 'text', 23),
('city.why.1.texte_template', 'Les institutions traditionnelles de {city} appliquent des critères stricts. Notre approche alternative évalue votre situation globale, pas uniquement votre pointage de crédit.', 'city', 'Pourquoi 1 texte', 'textarea', 24),
('city.why.2.titre', 'Besoin de financement rapide ?', 'city', 'Pourquoi 2 titre', 'text', 25),
('city.why.2.texte_template', 'Que vous soyez à {city} ou dans les environs, nous pouvons approuver votre dossier en 48 heures. Idéal pour saisir une opportunité immobilière ou faire face à une urgence financière.', 'city', 'Pourquoi 2 texte', 'textarea', 26),
('city.why.3.titre', 'Garantie immobilière', 'city', 'Pourquoi 3 titre', 'text', 27),
('city.why.3.texte_template', 'Si vous possédez un immeuble ou un terrain dans la région de {city}, vous pouvez utiliser votre équité comme garantie pour obtenir le financement dont vous avez besoin.', 'city', 'Pourquoi 3 texte', 'textarea', 28),
('city.why.4.titre', 'Confidentiel et professionnel', 'city', 'Pourquoi 4 titre', 'text', 29),
('city.why.4.texte', 'Depuis 1998, notre réputation repose sur la discrétion et le professionnalisme. Votre dossier est traité avec la plus grande confidentialité.', 'city', 'Pourquoi 4 texte', 'textarea', 30),
('city.faq.titre_template', 'Questions fréquentes — {city}', 'city', 'Template FAQ titre', 'text', 31),
('city.faq.1.q_template', 'Comment obtenir un prêt alternatif à {city} ?', 'city', 'FAQ 1 question', 'text', 32),
('city.faq.1.a_template', 'Remplissez notre formulaire en ligne ou appelez-nous au {phone}. Nous évaluons votre dossier et votre propriété dans la région de {city} pour vous proposer une solution adaptée. L''approbation peut se faire en 48 heures.', 'city', 'FAQ 1 réponse', 'textarea', 33),
('city.faq.2.q_template', 'Quelle est la différence entre un prêteur alternatif et une banque à {city} ?', 'city', 'FAQ 2 question', 'text', 34),
('city.faq.2.a_template', 'Contrairement aux banques traditionnelles de {city}, un prêteur alternatif comme Solutions Financement Fortier accorde davantage d''importance à la valeur de la garantie immobilière qu''au pointage de crédit. C''est idéal si vous avez été refusé ailleurs.', 'city', 'FAQ 2 réponse', 'textarea', 35),
('city.faq.3.q_template', 'Combien puis-je emprunter avec ma propriété à {city} ?', 'city', 'FAQ 3 question', 'text', 36),
('city.faq.3.a_template', 'Le montant dépend de la valeur de votre propriété à {city} et de l''équité disponible. Nous finançons généralement jusqu''à 75% de la valeur marchande de l''immeuble.', 'city', 'FAQ 3 réponse', 'textarea', 37),
('city.faq.4.q_template', 'Servez-vous toute la région {region} ?', 'city', 'FAQ 4 question', 'text', 38),
('city.faq.4.a_template', 'Oui, nous servons {city} et toute la région {region}, incluant {nearby} et les environs.', 'city', 'FAQ 4 réponse', 'textarea', 39),
('city.nearby.titre_template', 'Aussi disponible près de {city}', 'city', 'Template villes voisines', 'text', 40),
('city.cta.titre_template', 'Besoin de financement à {city} ?', 'city', 'Template CTA titre', 'text', 41),
('city.cta.soustitre', 'Remplissez notre formulaire en ligne et recevez une réponse en 48 heures.', 'city', 'CTA sous-titre', 'textarea', 42)
ON CONFLICT (cle) DO NOTHING;
